# Generated by Django 4.2.16 on 2024-10-24 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("common", "0001_initial"),
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Code"),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="Date")),
                (
                    "car_number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Cart Number"
                    ),
                ),
                (
                    "driver_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Driver Phone",
                    ),
                ),
                ("paid", models.BooleanField(default=False, verbose_name="Is Paid")),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Comment"),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[("transfer", "Transfer"), ("cash", "Cash")],
                        max_length=15,
                    ),
                ),
                (
                    "income",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Income",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (-1, "Rejected"),
                            (0, "Deleted"),
                            (1, "New"),
                            (2, "Filling"),
                            (3, "Started"),
                            (4, "At Factory"),
                            (5, "Dispatched"),
                            (6, "Location assigned"),
                            (9, "Finished"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Total Amount",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="clients.client",
                        verbose_name="Client",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "loading",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders_loading",
                        to="common.point",
                        verbose_name="Loading",
                    ),
                ),
                (
                    "unloading",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders_unloading",
                        to="common.point",
                        verbose_name="Un Loading",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "db_table": "orders",
            },
        ),
        migrations.CreateModel(
            name="OrderPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Amount"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("transfer", "Transfer"),
                            ("cash", "Cash"),
                            ("extra", "Extra"),
                        ],
                        max_length=15,
                        verbose_name="Type",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Comment"),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="payments/",
                        verbose_name="File",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="orders.order",
                        verbose_name="Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Payment",
                "verbose_name_plural": "Order Payments",
                "db_table": "order_payments",
            },
        ),
        migrations.AddConstraint(
            model_name="orderpayment",
            constraint=models.UniqueConstraint(
                fields=("order", "type"), name="unique_order_type"
            ),
        ),
    ]
