# Generated by Django 5.1.3 on 2024-11-25 12:04

import django.db.models.deletion
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Text"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("amount", "Amount"),
                            ("additional_amount", "Additional Amount"),
                            ("filled", "Filled"),
                            ("rollback", "Rollback"),
                            ("paid", "Paid"),
                            ("rollback_paid", "Paid"),
                            ("client_paid", "Client Paid"),
                            ("rollback_client_paid", "Client Paid"),
                        ],
                        default="create",
                        max_length=20,
                        verbose_name="Action",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Log",
                "verbose_name_plural": "Order Logs",
                "db_table": "order_logs",
            },
        ),
        migrations.CreateModel(
            name="OrderPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Amount"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("transfer", "Transfer"),
                            ("cash", "Cash"),
                            ("extra", "Extra"),
                        ],
                        max_length=15,
                        verbose_name="Type",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Comment"),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="payments/",
                        verbose_name="File",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Payment",
                "verbose_name_plural": "Order Payments",
                "db_table": "order_payments",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Code"),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="Date")),
                ("paid", models.BooleanField(default=False, verbose_name="Is Paid")),
                (
                    "client_paid",
                    models.BooleanField(default=False, verbose_name="Client is Paid"),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Comment"),
                ),
                (
                    "rejected_comment",
                    models.TextField(blank=True, null=True, verbose_name="Comment"),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[("transfer", "Transfer"), ("cash", "Cash")],
                        max_length=15,
                    ),
                ),
                (
                    "income",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Income",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (-1, "Rejected"),
                            (0, "Deleted"),
                            (1, "New"),
                            (2, "Filling"),
                            (3, "Started"),
                            (4, "At Factory"),
                            (5, "Loaded"),
                            (6, "Location assigned"),
                            (9, "Finished"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "car_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        validators=[utils.validators.VehicleNumberValidator()],
                        verbose_name="Car Number",
                    ),
                ),
                (
                    "driver_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        validators=[utils.validators.PhoneValidator()],
                        verbose_name="Driver Phone",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Total Amount",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="clients.client",
                        verbose_name="Client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "db_table": "orders",
            },
        ),
    ]
