# Generated by Django 5.1.3 on 2024-11-28 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accountant", "0002_initial"),
        ("common", "0001_initial"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="dispatcher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders_dispatcher",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Dispatcher",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="accountant.accountantinvoice",
                verbose_name="Invoice",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="loading",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders_loading",
                to="common.point",
                verbose_name="Loading",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="unloading",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders_unloading",
                to="common.point",
                verbose_name="Un Loading",
            ),
        ),
        migrations.AddField(
            model_name="orderlog",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="orders.order",
                verbose_name="Order",
            ),
        ),
        migrations.AddField(
            model_name="orderlog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="orderpayment",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="orders.order",
                verbose_name="Order",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderpayment",
            constraint=models.UniqueConstraint(
                fields=("order", "type"), name="unique_order_type"
            ),
        ),
    ]
