# Generated by Django 4.2.16 on 2024-11-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.IntegerField(
                choices=[
                    (-1, "Rejected"),
                    (0, "Deleted"),
                    (1, "New"),
                    (2, "Filling"),
                    (3, "Started"),
                    (4, "At Factory"),
                    (5, "Loaded"),
                    (6, "Location assigned"),
                    (9, "Finished"),
                ],
                default=1,
            ),
        ),
    ]
