# Generated by Django 4.2.16 on 2024-11-05 12:35

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="car_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[utils.validators.VehicleNumberValidator()],
                verbose_name="Car Number",
            ),
        ),
    ]
