# Generated by Django 4.2.16 on 2024-11-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="client_paid",
            field=models.BooleanField(default=False, verbose_name="Is Paid"),
        ),
    ]
