# Generated by Django 4.2.16 on 2024-11-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_client_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="client_paid",
            field=models.BooleanField(default=False, verbose_name="Client is Paid"),
        ),
    ]
