# Generated by Django 4.2.16 on 2024-11-08 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_order_car_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderlog",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="orders.order",
                verbose_name="Order",
            ),
        ),
    ]
