# Generated by Django 4.2.16 on 2024-11-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_orderlog_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="rejected_comment",
            field=models.TextField(blank=True, null=True, verbose_name="Comment"),
        ),
    ]
