# Generated by Django 5.1.3 on 2024-11-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_order_client_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("amount", "Amount"),
                    ("additional_amount", "Additional Amount"),
                    ("filled", "Filled"),
                    ("rollback", "Rollback"),
                    ("paid", "Paid"),
                    ("rollback_paid", "Paid"),
                    ("client_paid", "Client Paid"),
                    ("rollback_client_paid", "Client Paid"),
                ],
                default="create",
                max_length=20,
                verbose_name="Action",
            ),
        ),
    ]
