# Generated by Django 4.2.16 on 2024-11-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="rejected",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Rejected"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="comment",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Comment"
            ),
        ),
    ]
