# Generated by Django 4.2.16 on 2024-11-19 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="checker",
            new_name="receiver",
        ),
    ]
