version: '3.8'

services:
  aroba_web:
    build: .
    container_name: aroba_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ./static:/app/static
      - ./media:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - aroba_db

  aroba_db:
    image: postgres:14
    env_file:
      - .env
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      - DB_HOST=postgres_db
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

volumes:
  postgres_data:
