# Generated by Django 5.1.3 on 2024-11-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IMBCheckout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance", models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                "verbose_name": "IMB Checkout",
                "verbose_name_plural": "IMB Checkout",
                "db_table": "KassaApp_kassa",
                "managed": False,
            },
        ),
    ]
