# Generated by Django 5.1.3 on 2024-11-28 07:55

from django.db import migrations, models

import utils.customs.storages


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="Full name"),
                ),
                (
                    "truck_id",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Truck ID"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=9, unique=True, verbose_name="Phone number"
                    ),
                ),
                (
                    "car_type",
                    models.CharField(max_length=30, null=True, verbose_name="Car Type"),
                ),
                (
                    "car_model",
                    models.CharField(
                        max_length=30, null=True, verbose_name="Car Model"
                    ),
                ),
                (
                    "trailer_type",
                    models.CharField(
                        max_length=30, null=True, verbose_name="Trailer Type"
                    ),
                ),
                (
                    "is_blocked",
                    models.BooleanField(default=False, verbose_name="Is Blocked"),
                ),
                (
                    "is_contacted",
                    models.BooleanField(default=True, verbose_name="Is Contacted"),
                ),
                (
                    "trailer_front",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=utils.customs.storages.PublicStorage,
                        upload_to="contact_images/",
                        verbose_name="Trailer front",
                    ),
                ),
                (
                    "trailer_back",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=utils.customs.storages.PublicStorage,
                        upload_to="contact_images/",
                        verbose_name="Trailer back",
                    ),
                ),
                (
                    "license_front",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=utils.customs.storages.PublicStorage,
                        upload_to="contact_images/",
                        verbose_name="License front",
                    ),
                ),
                (
                    "license_back",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=utils.customs.storages.PublicStorage,
                        upload_to="contact_images/",
                        verbose_name="License back",
                    ),
                ),
                (
                    "track_front",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=utils.customs.storages.PublicStorage,
                        upload_to="contact_images/",
                        verbose_name="Track front",
                    ),
                ),
                (
                    "track_back",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=utils.customs.storages.PublicStorage,
                        upload_to="contact_images/",
                        verbose_name="Track back",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
                "db_table": "contacts",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="IMBCheckout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance", models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                "verbose_name": "Checkout",
                "verbose_name_plural": "Checkout",
                "db_table": "KassaApp_kassa",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="IMBTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("comment", models.CharField(max_length=250)),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (1, "Agentdan kirim"),
                            (2, "Asosiy kirim"),
                            (3, "Agentga chiqim"),
                            (4, "Boshqa chiqim"),
                        ],
                        db_index=True,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "check_url",
                    models.URLField(
                        blank=True, max_length=50, null=True, verbose_name="Check"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("approved", "Approved"), ("cancelled", "Cancelled")],
                        default="approved",
                        max_length=50,
                        verbose_name="Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "db_table": "KassaApp_transactions",
                "managed": False,
            },
        ),
    ]
