# Generated by Django 4.2.16 on 2024-11-10 05:34

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="Full Name"),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=20,
                        validators=[utils.validators.PhoneValidator()],
                        verbose_name="Phone",
                    ),
                ),
                (
                    "car_number",
                    models.CharField(
                        max_length=100,
                        validators=[utils.validators.VehicleNumberValidator()],
                        verbose_name="Car number",
                    ),
                ),
                (
                    "trailer_front",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contact_images/",
                        verbose_name="Trailer front",
                    ),
                ),
                (
                    "trailer_back",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contact_images/",
                        verbose_name="Trailer back",
                    ),
                ),
                (
                    "license_front",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contact_images/",
                        verbose_name="License front",
                    ),
                ),
                (
                    "license_back",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contact_images/",
                        verbose_name="License back",
                    ),
                ),
                (
                    "track_front",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contact_images/",
                        verbose_name="Track front",
                    ),
                ),
                (
                    "track_back",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contact_images/",
                        verbose_name="Track back",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
                "db_table": "contacts",
            },
        ),
    ]
