# Generated by Django 4.2.16 on 2024-11-06 05:02

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="car_number",
            field=models.CharField(
                default=None,
                max_length=100,
                validators=[utils.validators.VehicleNumberValidator()],
                verbose_name="Car number",
            ),
            preserve_default=False,
        ),
    ]
