# Generated by Django 4.2.16 on 2024-10-24 09:12

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="point",
            managers=[
                ("active_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="point",
            name="deleted",
            field=models.BooleanField(default=False, verbose_name="Active"),
        ),
    ]
