# Generated by Django 4.2.16 on 2024-10-30 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="point",
            managers=[],
        ),
    ]
