# Generated by Django 4.2.16 on 2024-10-31 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_alter_point_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="point",
            name="deleted",
            field=models.BooleanField(default=False, verbose_name="Deleted"),
        ),
    ]
