# Generated by Django 4.2.16 on 2024-11-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiroute",
            name="route",
            field=models.CharField(
                choices=[
                    ("/api/v1/users/", "Users"),
                    ("/api/v1/common/", "Common"),
                    ("/api/v1/clients/", "Clients"),
                    ("/api/v1/orders/", "Orders"),
                    ("/api/v1/auth/", "Auth"),
                    ("/api/v1/managers/", "Managers"),
                    ("/api/v1/dispatchers/", "Dispatchers"),
                ],
                max_length=50,
                verbose_name="route",
            ),
        ),
        migrations.AddConstraint(
            model_name="apiroute",
            constraint=models.UniqueConstraint(
                fields=("route", "name", "dynamic", "method"), name="api_routes_unique"
            ),
        ),
    ]
