# Generated by Django 4.2.16 on 2024-11-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="apis",
        ),
        migrations.AddField(
            model_name="user",
            name="actions",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="users.action"
            ),
        ),
    ]
