# Generated by Django 4.2.16 on 2024-10-22 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="api",
            name="route",
            field=models.CharField(
                choices=[("/api/v1/users/", "Users"), ("/api/v1/common/", "Common")],
                max_length=100,
                unique=True,
                verbose_name="route",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="users.role",
            ),
        ),
    ]
