# Generated by Django 4.2.16 on 2024-10-30 08:54

import apps.users.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ExtendedContentType",
            new_name="ExtendedModule",
        ),
        migrations.DeleteModel(
            name="ContentType",
        ),
        migrations.CreateModel(
            name="Module",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("contenttypes.contenttype",),
            managers=[
                ("objects", apps.users.managers.ModuleManager()),
            ],
        ),
    ]
