# Generated by Django 4.2.16 on 2024-10-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_api_route_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="api",
            name="route",
            field=models.CharField(
                choices=[("/api/v1/users/", "Users"), ("/api/v1/common/", "Common")],
                max_length=50,
                verbose_name="route",
            ),
        ),
    ]
