# Generated by Django 4.2.16 on 2024-11-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_apis_user_actions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiroute",
            name="dynamic",
            field=models.BooleanField(default=False, verbose_name="dynamic"),
        ),
    ]
