# Generated by Django 4.2.16 on 2024-10-24 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_module_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiroute",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="apiroute",
            name="route",
            field=models.CharField(
                choices=[
                    ("/api/v1/users/", "Users"),
                    ("/api/v1/common/", "Common"),
                    ("/api/v1/clients/", "Clients"),
                    ("/api/v1/orders/", "Orders"),
                ],
                max_length=50,
                verbose_name="route",
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="name",
            field=models.CharField(
                default=None, max_length=150, unique=True, verbose_name="name"
            ),
            preserve_default=False,
        ),
    ]
