# Generated by Django 4.2.16 on 2024-11-14 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_section_module_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="order",
            field=models.IntegerField(default=0, verbose_name="order"),
        ),
        migrations.AlterField(
            model_name="module",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modules",
                to="users.section",
                verbose_name="section",
            ),
        ),
    ]
