# Generated by Django 4.2.16 on 2024-11-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_section_order_alter_module_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiroute",
            name="route",
            field=models.CharField(
                choices=[
                    ("/api/v1/users/", "Users"),
                    ("/api/v1/common/", "Common"),
                    ("/api/v1/clients/", "Clients"),
                    ("/api/v1/orders/", "Orders"),
                    ("/api/v1/auth/", "Auth"),
                    ("/api/v1/managers/", "Managers"),
                    ("/api/v1/dispatchers/", "Dispatchers"),
                    ("/api/v1/checkout/", "Checkout"),
                    ("/api/v1/accountant/", "Accountant"),
                ],
                max_length=50,
                verbose_name="route",
            ),
        ),
    ]
