# Generated by Django 4.2.16 on 2024-10-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_api_route"),
    ]

    operations = [
        migrations.AlterField(
            model_name="api",
            name="dynamic",
            field=models.CharField(
                choices=[("1", "Yes"), ("0", "No")], verbose_name="dynamic"
            ),
        ),
    ]
