# Generated by Django 4.2.16 on 2024-11-02 11:54

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_apiroute_dynamic"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=15,
                validators=[utils.validators.PhoneValidator],
                verbose_name="phone number",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                blank=True, upload_to="users/", verbose_name="Photo"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="actions",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                to="users.action",
                verbose_name="Actions",
            ),
        ),
    ]
