# Generated by Django 4.2.16 on 2024-11-02 12:02

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_phone_user_photo_alter_user_actions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[utils.validators.PhoneValidator],
                verbose_name="phone number",
            ),
        ),
    ]
