upstream aroba_project {
    server aroba_web:8000
}

server {
    listen 80;
    server_name your_domain.com;


     location / {
        include proxy_params;
        proxy_pass http://aroba_project;
    }

    location /static/ {
        alias /aroba/static/;
    }

    location /media/ {
        alias /aroba/media/;
    }
}

