# Generated by Django 5.1.3 on 2024-11-25 12:04

import django.db.models.deletion
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Client name")),
                (
                    "phone",
                    models.CharField(
                        max_length=20,
                        validators=[utils.validators.PhoneValidator()],
                        verbose_name="Client phone",
                    ),
                ),
                (
                    "requisite",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Requisite comment",
                    ),
                ),
                (
                    "requisite_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="clients/",
                        verbose_name="Requisite file",
                    ),
                ),
                ("deleted", models.BooleanField(default=False, verbose_name="Deleted")),
                (
                    "inn",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Inner client",
                    ),
                ),
                (
                    "customer",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Customer"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("transfer", "Transfer"), ("cash", "Cash")],
                        default="cash",
                        max_length=15,
                        verbose_name="Route type",
                    ),
                ),
                (
                    "accounting_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        validators=[utils.validators.PhoneValidator()],
                        verbose_name="Accounting phone number",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "db_table": "clients",
            },
        ),
        migrations.CreateModel(
            name="ClientRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Amount"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to="clients.client",
                        verbose_name="Client",
                    ),
                ),
                (
                    "loading",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="client_routes_loading",
                        to="common.point",
                        verbose_name="Loading",
                    ),
                ),
                (
                    "unloading",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="client_routes_unloading",
                        to="common.point",
                        verbose_name="UnLoading",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client route",
                "verbose_name_plural": "Client routes",
                "db_table": "clients_route",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("loading", "unloading", "client"),
                        name="unique_client_router",
                    )
                ],
            },
        ),
    ]
