# Generated by Django 4.2.16 on 2024-10-23 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Client name")),
                ("phone", models.CharField(max_length=20, verbose_name="Client phone")),
                (
                    "requisite",
                    models.CharField(max_length=255, verbose_name="Requisite comment"),
                ),
                (
                    "requisite_file",
                    models.FileField(
                        upload_to="clients/", verbose_name="Requisite file"
                    ),
                ),
                (
                    "accounting_phone",
                    models.CharField(
                        max_length=20, verbose_name="Account phone number"
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "db_table": "clients",
            },
        ),
        migrations.CreateModel(
            name="ClientRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Amount"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to="clients.client",
                        verbose_name="Client",
                    ),
                ),
                (
                    "loading",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="client_routes_loading",
                        to="common.point",
                        verbose_name="Loading",
                    ),
                ),
                (
                    "unloading",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="client_routes_unloading",
                        to="common.point",
                        verbose_name="Loading",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client route",
                "verbose_name_plural": "Client routes",
                "db_table": "clients_route",
            },
        ),
    ]
