# Generated by Django 4.2.16 on 2024-11-04 12:29

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="accounting_phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[utils.validators.PhoneValidator()],
                verbose_name="Accounting phone number",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="requisite",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Requisite comment"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="requisite_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="clients/",
                verbose_name="Requisite file",
            ),
        ),
    ]
