# Generated by Django 4.2.16 on 2024-11-01 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_alter_point_deleted"),
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientroute",
            name="unloading",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="client_routes_unloading",
                to="common.point",
                verbose_name="UnLoading",
            ),
        ),
    ]
