# Generated by Django 4.2.16 on 2024-10-24 09:36

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="client",
            managers=[
                ("active_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="client",
            name="deleted",
            field=models.BooleanField(default=False, verbose_name="Deleted"),
        ),
        migrations.AddField(
            model_name="clientroute",
            name="type",
            field=models.CharField(
                choices=[("transfer", "Transfer"), ("cash", "Cash")],
                default="cash",
                max_length=15,
                verbose_name="Route type",
            ),
        ),
    ]
