# Generated by Django 4.2.16 on 2024-11-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="clientroute",
            name="unique_client_router",
        ),
        migrations.RemoveField(
            model_name="clientroute",
            name="type",
        ),
        migrations.AddField(
            model_name="client",
            name="type",
            field=models.CharField(
                choices=[("transfer", "Transfer"), ("cash", "Cash")],
                default="cash",
                max_length=15,
                verbose_name="Route type",
            ),
        ),
        migrations.AddConstraint(
            model_name="clientroute",
            constraint=models.UniqueConstraint(
                fields=("loading", "unloading", "client"), name="unique_client_router"
            ),
        ),
    ]
