# Generated by Django 4.2.16 on 2024-11-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "clients",
            "0002_alter_client_accounting_phone_alter_client_requisite_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="customer",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Customer"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="inn",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Inner client"
            ),
        ),
    ]
