# Generated by Django 4.2.16 on 2024-10-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_alter_client_managers_client_deleted_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="clientroute",
            constraint=models.UniqueConstraint(
                fields=("loading", "unloading", "client", "type"),
                name="unique_client_router",
            ),
        ),
    ]
