# Generated by Django 4.2.16 on 2024-11-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_client_customer_client_inn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientroute",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=15, verbose_name="Amount"
            ),
        ),
    ]
