# Generated by Django 4.2.16 on 2024-11-11 09:39

from django.db import migrations, models
import django.db.models.deletion
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountantInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("customer", models.CharField(max_length=50, verbose_name="Customer")),
                ("inn", models.CharField(max_length=15, verbose_name="Inner client")),
                (
                    "accounting_phone",
                    models.CharField(
                        max_length=20,
                        validators=[utils.validators.PhoneValidator()],
                        verbose_name="Accounting phone number",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="clients.client",
                        verbose_name="Client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "db_table": "accountant_invoices",
            },
        ),
    ]
