# Generated by Django 5.1.3 on 2024-11-28 07:55

import django.db.models.deletion
from django.db import migrations, models

import utils.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountantInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=30,
                        verbose_name="Amount",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                    ),
                ),
                (
                    "customer",
                    models.CharField(max_length=50, null=True, verbose_name="Customer"),
                ),
                (
                    "inn",
                    models.CharField(
                        max_length=15, null=True, verbose_name="Inner client"
                    ),
                ),
                (
                    "accounting_phone",
                    models.CharField(
                        max_length=20,
                        validators=[utils.validators.PhoneValidator()],
                        verbose_name="Accounting phone number",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="clients.client",
                        verbose_name="Client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "db_table": "accountant_invoices",
            },
        ),
    ]
