# Generated by Django 5.1.3 on 2024-11-28 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accountant", "0001_initial"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="accountantinvoice",
            name="creator",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="accountantinvoice",
            name="past_orders",
            field=models.ManyToManyField(
                related_name="invoices", to="orders.order", verbose_name="Past orders"
            ),
        ),
    ]
