# Generated by Django 4.2.16 on 2024-11-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountantinvoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
            ),
        ),
    ]
