# Generated by Django 4.2.16 on 2024-11-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountant", "0002_accountantinvoice_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountantinvoice",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=30, verbose_name="Amount"
            ),
        ),
    ]
