# Generated by Django 4.2.16 on 2024-11-16 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_invoice"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accountant", "0003_accountantinvoice_total_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountantinvoice",
            name="creator",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="accountantinvoice",
            name="past_orders",
            field=models.ManyToManyField(
                related_name="invoices", to="orders.order", verbose_name="Past orders"
            ),
        ),
    ]
