# Generated by Django 4.2.16 on 2024-11-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountant", "0004_accountantinvoice_creator_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountantinvoice",
            name="customer",
            field=models.CharField(max_length=50, null=True, verbose_name="Customer"),
        ),
    ]
