# Generated by Django 4.2.16 on 2024-11-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountant", "0005_alter_accountantinvoice_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountantinvoice",
            name="inn",
            field=models.CharField(
                max_length=15, null=True, verbose_name="Inner client"
            ),
        ),
    ]
